[package]
name = "hexora_io"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
walkdir = "2.5.0"
zip = "6.0.0"
tar = "0.4"
flate2 = "1.0"

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true

